kind: pipeline
type: docker
name: cd

steps:
- name: deploy
  image: appleboy/drone-ssh
  environment:
    SSH_DEPLOY_SHELL:
      from_secret: ssh_deploy_shell
    DOCKER_TAG:
      from_secret: docker_tag
  settings:
    host:
      from_secret: ssh_host
    port:
      from_secret: ssh_port
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    envs:
      - ssh_deploy_shell
      - docker_tag
    script:
      - $SSH_DEPLOY_SHELL -d music -e $DOCKER_TAG -i music-be -p 4001 -u /api

trigger:
  branch:
    - main